# Generated by Django 5.0.4 on 2024-05-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twf", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dictionary",
            name="label",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="dictionary",
            name="type",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
