# Generated by Django 5.0.4 on 2024-05-05 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twf", "0003_datevariation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagetag",
            name="normalized_variation",
        ),
        migrations.AddField(
            model_name="pagetag",
            name="date_variation_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="twf.datevariation",
            ),
        ),
    ]
