# Generated by Django 5.0.4 on 2024-05-23 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twf", "0004_remove_pagetag_normalized_variation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="geonames_username",
            field=models.CharField(
                blank=True,
                help_text="The username for the Geonames API.",
                max_length=100,
                null=True,
                verbose_name="Geonames Username",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="openai_api_key",
            field=models.CharField(
                blank=True,
                help_text="The API key for the Open AI API.",
                max_length=100,
                null=True,
                verbose_name="Open AI API Key",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="transkribus_password",
            field=models.CharField(
                blank=True,
                help_text="The password for the Transkribus API.",
                max_length=100,
                null=True,
                verbose_name="Transkribus Password",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="transkribus_username",
            field=models.CharField(
                blank=True,
                help_text="The username for the Transkribus API.",
                max_length=100,
                null=True,
                verbose_name="Transkribus Username",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="collection_id",
            field=models.CharField(
                help_text="The Transkribus collection ID. Needed to export your data from Transkribus.",
                max_length=30,
                verbose_name="Transkribus Collection ID",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The description of the project. Should be brief. Can be used in data exports.",
                verbose_name="Project Description",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="downloaded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The time the last export was downloaded.",
                null=True,
                verbose_name="Last Export Downloaded At",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="downloaded_zip_file",
            field=models.FileField(
                blank=True,
                help_text="The last downloaded export file.",
                null=True,
                upload_to="transkribus_exports/",
                verbose_name="Last Export File",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="ignored_tag_types",
            field=models.JSONField(
                default=dict,
                help_text="A list of tag types to ignore and a list of tag typeswhich are special (e.g. dates).",
                verbose_name="Special Tag Types",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="job_download_url",
            field=models.URLField(
                blank=True,
                help_text="The download URL of the last requested export.This value is set by the system and should only be changed to manually point TWF to a finished export job.",
                null=True,
                verbose_name="Transkribus Job Download URL",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(
                help_text="The members of the project. Their roles can be adjustedin the user management section.",
                related_name="projects",
                to="twf.userprofile",
                verbose_name="Project Members",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="metadata_google_doc_id_column",
            field=models.CharField(
                blank=True,
                help_text="The name of the column containing the document IDs",
                max_length=50,
                null=True,
                verbose_name="Google Sheet Document ID Column Name",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="metadata_google_sheet_id",
            field=models.CharField(
                blank=True,
                help_text="The ID of the Google Sheet containing metadata",
                max_length=100,
                null=True,
                verbose_name="Google Sheet ID",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="metadata_google_sheet_range",
            field=models.CharField(
                blank=True,
                help_text="The range of the Google Sheet containing metadata",
                max_length=100,
                null=True,
                verbose_name="Google Sheet Data Range",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="metadata_google_title_column",
            field=models.CharField(
                blank=True,
                help_text="The name of the column containing the document titles",
                max_length=50,
                null=True,
                verbose_name="Google Sheet Title Column Name",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="metadata_google_valid_columns",
            field=models.CharField(
                blank=True,
                help_text="A coma-separated list of valid column names for metadata. Leave blank for all columns.",
                max_length=512,
                null=True,
                verbose_name="Google Sheet Valid Columns",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_projects",
                to="twf.userprofile",
                verbose_name="Project Owner",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed")],
                default="open",
                help_text="The status of the project.",
                max_length=10,
                verbose_name="Project Status",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="tag_type_translator",
            field=models.JSONField(
                default=dict,
                help_text="A dictionary to translate tag types into dictionary types if they are not equal.",
                verbose_name="Tag Type Translator",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(
                help_text="The title of the project. Can be used in data exports.",
                max_length=100,
                verbose_name="Project Title",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="transkribus_job_id",
            field=models.CharField(
                blank=True,
                help_text="This value is set by the system and should only be changed to manually point TWF to a finished export job.",
                max_length=30,
                null=True,
                verbose_name="Transkribus Job ID",
            ),
        ),
    ]
