# Generated by Django 5.0.4 on 2024-06-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twf", "0006_project_selected_dictionaries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="selected_dictionaries",
            field=models.ManyToManyField(
                blank=True,
                help_text="The dictionaries selected for this project.",
                related_name="selected_projects",
                to="twf.dictionary",
                verbose_name="Selected Dictionaries",
            ),
        ),
    ]
