# Generated by Django 5.0.4 on 2024-07-04 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("twf", "0010_collection_project"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="collectionitem",
            unique_together=set(),
        ),
    ]
