# Generated by Django 5.0.4 on 2024-07-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twf", "0011_alter_collectionitem_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionitem",
            name="title",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
