# Generated by Django 5.0.4 on 2024-08-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twf", "0012_collectionitem_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionitem",
            name="marked_as_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="marked_as_faulty",
            field=models.BooleanField(default=False),
        ),
    ]
