# Generated by Django 5.0.4 on 2024-08-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twf", "0013_collectionitem_marked_as_done_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="document_metadata_fields",
            field=models.JSONField(
                default=dict,
                help_text="A dictionary of metadata fields for documents.",
                verbose_name="Document Metadata Fields",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="page_metadata_fields",
            field=models.JSONField(
                default=dict,
                help_text="A dictionary of metadata fields for pages.",
                verbose_name="Page Metadata Fields",
            ),
        ),
    ]
