# Generated by Django 5.0.4 on 2024-09-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twf", "0015_alter_collectionitem_document_configuration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("reviewed", "Reviewed"),
                    ("faulty", "Faulty"),
                ],
                default="open",
                max_length=10,
            ),
        ),
    ]
