# Generated by Django 5.0.4 on 2024-09-06 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("twf", "0016_collectionitem_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collectionitem",
            name="marked_as_done",
        ),
        migrations.RemoveField(
            model_name="collectionitem",
            name="marked_as_faulty",
        ),
    ]
