# Generated by Django 5.0.4 on 2024-09-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twf", "0017_remove_collectionitem_marked_as_done_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionitem",
            name="review_notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
